/*
 * Licencia GPL.
 * Desarrollado por: William Sánchez
 * El software se proporciona "TAL CUAL", sin garantía de ningún tipo,
 * expresa o implícita, incluyendo pero no limitado a las garantías de
 * comerciabilidad y adecuación para un particular son rechazadas.
 * En ningún caso el autor será responsable por cualquier reclamo,
 * daño u otra responsabilidad, ya sea en una acción de contrato,
 * agravio o cualquier otro motivo, de o en relación con el software
 * o el uso u otros tratos en el software.
 * 
 */
package Views;

/**
 *
 * @author William Sanchez
 */
public class ContactFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PersonForm
     */
    public ContactFrame() {
        initComponents();
        setController();
    }
    private void setController(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        selectButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(19, 19, 52, 16);

        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(19, 61, 52, 16);
        getContentPane().add(firstNameTextField);
        firstNameTextField.setBounds(89, 15, 507, 24);
        getContentPane().add(lastNameTextField);
        lastNameTextField.setBounds(89, 57, 507, 24);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 93, 608, 2);

        selectButton.setText("Seleccionar");
        selectButton.setActionCommand("select");
        getContentPane().add(selectButton);
        selectButton.setBounds(43, 331, 98, 32);

        clearButton.setText("Limpiar");
        clearButton.setActionCommand("clear");
        getContentPane().add(clearButton);
        clearButton.setBounds(190, 330, 73, 32);

        saveButton.setText("Guardar");
        saveButton.setActionCommand("save");
        getContentPane().add(saveButton);
        saveButton.setBounds(280, 330, 76, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 570, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
                               
    public void clear(){
        firstNameTextField.setText("");
        lastNameTextField.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
